### ISSUE TITLE
Remove archive images alignment

### ISSUE THREAD

**Issue by raduconst** [pixelgrade/patch-lite#2]
@georgeolaru Aici e o intrebare pentru tine, de 100 de puncte: cum zici ca ar arata totul daca am scoate acea aliniere a imaginilor in functie de aspect ratio? Eu am scos si am pus ca imaginile sa apara primele, dupa care titlul si textul: https://cl.ly/1p2R0s45172a
Am facut asta in ideea in care (ma gandesc) acel layout sa fie valabil doar in varianta Pro. Acum am nevoie de un sfat daca asta ar fi o abordare buna sau nu.

**Comment by georgeolaru** [comment]
@raduconst Hehe, e o idee buna — sugereaza o varianta "free" 😉  Zic sa incercam si sa vedem. 

PS: poate putem reusi asta doar din CSS  👀

**Comment by vladolaru** [comment]
@raduconst Buna ideea. Nu o putem pacali fortand ca toate imaginile sa "aiba" aspect ratio-ul landscape (atat pe arhive cat si pe single)?

**Comment by georgeolaru** [comment]
@vladolaru cred ca "landscape" e ala care genereaza acel layout cu suprapuneri —  mai degraba "square" e cel care mentine layout-ul cumine :)

**Comment by raduconst** [comment]
@georgeolaru @vladolaru Cu square am facut acel screenshot deci asta ar fi "raspunsul corect". Dau imediat un push cu modificarea si putem discuta mai multe despre cum se pliaza.
