### ISSUE TITLE
Gutenberg Editor font is different than the front-end font

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/patch-lite#29]
When I edit a post or page using the latest version of Patch Lite (1.3.1) I noticed that the font displayed is different than the one displayed when I publish or preview the post.

Here's proof -> https://share.getcloudapp.com/eDu9gJ65

**Comment by madalingorbanescu** [comment]
Closed in 2093c7be8843d5f2b53be583953e2e80c13d4c87
